/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#f57c00",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#cce5ff",
        "surface-container-highest": "#dae2fd",
        "primary-fixed-dim": "#ffb786",
        "on-primary-fixed-variant": "#723600",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#001d31",
        "on-error-container": "#93000a",
        "on-primary-container": "#572800",
        "on-secondary-fixed": "#410003",
        "secondary-fixed": "#ffdad6",
        "surface-container-low": "#f2f3ff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#ffb3ac",
        "inverse-surface": "#283044",
        outline: "#8b7263",
        primary: "#964900",
        "surface-container": "#eaedff",
        "on-surface": "#131b2e",
        "on-secondary-fixed-variant": "#930010",
        "surface-dim": "#d2d9f4",
        "inverse-on-surface": "#eef0ff",
        "surface-bright": "#faf8ff",
        "primary-fixed": "#ffdcc6",
        "on-surface-variant": "#574235",
        background: "#faf8ff",
        "surface-container-high": "#e2e7ff",
        "on-error": "#ffffff",
        "outline-variant": "#dec1af",
        "tertiary-fixed-dim": "#93ccff",
        "on-tertiary-container": "#003757",
        secondary: "#b6171e",
        "on-tertiary-fixed-variant": "#004b73",
        "on-secondary-container": "#fffbff",
        "on-secondary": "#ffffff",
        "on-background": "#131b2e",
        "tertiary-container": "#43a4e9",
        error: "#ba1a1a",
        "surface-tint": "#964900",
        "on-primary": "#ffffff",
        tertiary: "#006398",
        surface: "#faf8ff",
        "inverse-primary": "#ffb786",
        "surface-variant": "#dae2fd",
        "on-primary-fixed": "#311300",
        "secondary-container": "#da3433",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "margin-mobile": "1rem",
        "gutter-mobile": "1rem",
        margin: "2rem",
        "space-xl": "2.5rem",
        "space-xs": "0.25rem",
        gutter: "1.5rem",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-xl-mobile": ["32px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "800" }],
        "headline-xl": ["44px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
